// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: simpleagent/model.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostnameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HostnameRequest) Reset() {
	*x = HostnameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleagent_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostnameRequest) ProtoMessage() {}

func (x *HostnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simpleagent_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostnameRequest.ProtoReflect.Descriptor instead.
func (*HostnameRequest) Descriptor() ([]byte, []int) {
	return file_simpleagent_model_proto_rawDescGZIP(), []int{0}
}

type HostnameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *HostnameReply) Reset() {
	*x = HostnameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleagent_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostnameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostnameReply) ProtoMessage() {}

func (x *HostnameReply) ProtoReflect() protoreflect.Message {
	mi := &file_simpleagent_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostnameReply.ProtoReflect.Descriptor instead.
func (*HostnameReply) Descriptor() ([]byte, []int) {
	return file_simpleagent_model_proto_rawDescGZIP(), []int{1}
}

func (x *HostnameReply) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ExecTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *ExecTaskRequest) Reset() {
	*x = ExecTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleagent_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTaskRequest) ProtoMessage() {}

func (x *ExecTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simpleagent_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecTaskRequest) Descriptor() ([]byte, []int) {
	return file_simpleagent_model_proto_rawDescGZIP(), []int{2}
}

func (x *ExecTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecTaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exectasks []*ExecTaskRequest `protobuf:"bytes,1,rep,name=exectasks,proto3" json:"exectasks,omitempty"`
}

func (x *ExecTasksRequest) Reset() {
	*x = ExecTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleagent_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTasksRequest) ProtoMessage() {}

func (x *ExecTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simpleagent_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTasksRequest.ProtoReflect.Descriptor instead.
func (*ExecTasksRequest) Descriptor() ([]byte, []int) {
	return file_simpleagent_model_proto_rawDescGZIP(), []int{3}
}

func (x *ExecTasksRequest) GetExectasks() []*ExecTaskRequest {
	if x != nil {
		return x.Exectasks
	}
	return nil
}

type ExecTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid    string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cmd     string `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Result  string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error   string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Success bool   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ExecTaskReply) Reset() {
	*x = ExecTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleagent_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTaskReply) ProtoMessage() {}

func (x *ExecTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_simpleagent_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTaskReply.ProtoReflect.Descriptor instead.
func (*ExecTaskReply) Descriptor() ([]byte, []int) {
	return file_simpleagent_model_proto_rawDescGZIP(), []int{4}
}

func (x *ExecTaskReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecTaskReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ExecTaskReply) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ExecTaskReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecTaskReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecTaskReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExecTasksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecTasksres []*ExecTaskReply `protobuf:"bytes,1,rep,name=execTasksres,proto3" json:"execTasksres,omitempty"`
}

func (x *ExecTasksReply) Reset() {
	*x = ExecTasksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleagent_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTasksReply) ProtoMessage() {}

func (x *ExecTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_simpleagent_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTasksReply.ProtoReflect.Descriptor instead.
func (*ExecTasksReply) Descriptor() ([]byte, []int) {
	return file_simpleagent_model_proto_rawDescGZIP(), []int{5}
}

func (x *ExecTasksReply) GetExecTasksres() []*ExecTaskReply {
	if x != nil {
		return x.ExecTasksres
	}
	return nil
}

var File_simpleagent_model_proto protoreflect.FileDescriptor

var file_simpleagent_model_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x66, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x11, 0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x0d, 0x48, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x53, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x09,
	0x65, 0x78, 0x65, 0x63, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x66, 0x79, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x91, 0x01,
	0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x55, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x79, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x0c, 0x65, 0x78, 0x65, 0x63,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x72, 0x65, 0x73, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_simpleagent_model_proto_rawDescOnce sync.Once
	file_simpleagent_model_proto_rawDescData = file_simpleagent_model_proto_rawDesc
)

func file_simpleagent_model_proto_rawDescGZIP() []byte {
	file_simpleagent_model_proto_rawDescOnce.Do(func() {
		file_simpleagent_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_simpleagent_model_proto_rawDescData)
	})
	return file_simpleagent_model_proto_rawDescData
}

var file_simpleagent_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_simpleagent_model_proto_goTypes = []interface{}{
	(*HostnameRequest)(nil),  // 0: simpleagent.model.v1.HostnameRequest
	(*HostnameReply)(nil),    // 1: simpleagent.model.v1.HostnameReply
	(*ExecTaskRequest)(nil),  // 2: simpleagent.model.v1.ExecTaskRequest
	(*ExecTasksRequest)(nil), // 3: simpleagent.model.v1.ExecTasksRequest
	(*ExecTaskReply)(nil),    // 4: simpleagent.model.v1.ExecTaskReply
	(*ExecTasksReply)(nil),   // 5: simpleagent.model.v1.ExecTasksReply
}
var file_simpleagent_model_proto_depIdxs = []int32{
	2, // 0: simpleagent.model.v1.ExecTasksRequest.exectasks:type_name -> simpleagent.model.v1.ExecTaskRequest
	4, // 1: simpleagent.model.v1.ExecTasksReply.execTasksres:type_name -> simpleagent.model.v1.ExecTaskReply
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_simpleagent_model_proto_init() }
func file_simpleagent_model_proto_init() {
	if File_simpleagent_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simpleagent_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostnameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpleagent_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostnameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpleagent_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpleagent_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpleagent_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpleagent_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecTasksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simpleagent_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simpleagent_model_proto_goTypes,
		DependencyIndexes: file_simpleagent_model_proto_depIdxs,
		MessageInfos:      file_simpleagent_model_proto_msgTypes,
	}.Build()
	File_simpleagent_model_proto = out.File
	file_simpleagent_model_proto_rawDesc = nil
	file_simpleagent_model_proto_goTypes = nil
	file_simpleagent_model_proto_depIdxs = nil
}
